Sending stop command to LabVIEW application
SBNSoftware/sbndaq-artdaq pull request #101
Opened 2023-05-08 23:06 UTC by dtorretta56

### Description

This code will send the stop command to the LabVIEW application via a TCP/IP socket already opened

### Testing details
_ NEEDS a new version of LabVIEW project (that listens and acts upon receiving the STOP command)
- tested at SBN-FD 
- run numbers: 9782-9786, 9788, 9798-9806

2023-05-09 16:45 UTC, aaduszki requested changes

2023-05-09 16:45 UTC, aaduszki commented on sbndaq-artdaq/Generators/ICARUS/ICARUSTriggerV3_generator.cc
> +    if (doThis == 1) {
Could you please add a comment on what does this code do, and why it is not executed?

2023-05-09 16:45 UTC, aaduszki commented on sbndaq-artdaq/Generators/ICARUS/ICARUSTriggerV3_generator.cc
> +  //return -1;
I would suggest removing this, and other commented out lines.

2023-05-09 16:45 UTC, aaduszki commented on sbndaq-artdaq/Generators/ICARUS/ICARUSTriggerV3_generator.cc
> +    retries--;
Does this do anything, given the while loop above is commented out?

2023-05-09 21:32 UTC, aaduszki approved these changes

2023-05-10 11:38 UTC, jzettle approved these changes

2023-05-10 23:35 UTC, merged