Feature/bslater trigger
SBNSoftware/sbndaq-artdaq pull request #127
Opened 2023-11-14 19:23 UTC by bslater2

### Description

Amended PTB Board Reader to send all trigger rate metrics to Grafana and adjusted metric levels to reflect desired level for commissioning run

### Related Repository Branches

N/A

### Testing details

- *Where it was tested*: SBN-ND
- *Run number associated with test*: Everything in /data/Trigger on evb03 used this but was mostly passively tested by checking Grafana during other runs (eg. 9262-9664).
- Other information: N/A

2023-11-28 22:59 UTC, terezakroupa reviewed
Thank you so much @bslater2 for this! I have two minor and non-critical comments below, otherwise it looks great.

A general comment - it would be useful to submit a related PR to sbndaq to update the standard ptb01.fcl to include the metrics.

2023-11-28 22:59 UTC, terezakroupa commented on sbndaq-artdaq/Generators/SBND/TriggerBoardReader_generator.cc
> +	  //artdaq::Globals::metricMan_->sendMetric("PTB_Beam_Eff", beam_eff, "ratio", 11, artdaq::MetricMode::Average) ;
I think it's ok to just remove this as well as the "good part rate" instead of commenting it out

2023-11-28 22:59 UTC, terezakroupa commented on sbndaq-artdaq/Generators/SBND/TriggerBoardReader_generator.cc
> +	  //artdaq::Globals::metricMan_->sendMetric("PTB_CS_rate",  cs_rate,  "Hz", 11, artdaq::MetricMode::Average) ;
This one is the rate of channel status words, which could be potentially useful. Maybe we can set it as very low priority, but keep it?

2023-12-01 11:38 UTC, bslater2 commented
Need to still confirm Lan's changes are working as desired, having some issues with downstream modules

2023-12-05 16:35 UTC, gennadiy-fnal requested changes
This pull request needs to be split into 3 separate pull requests: 1. CAEN1730 code; 2. Trigger Boardreader code; and 3. Analyzer modules. The CAEN1730 pull request needs to be thoroughly reviewed by 2 members of Icarus and 2 members of SBND collaboration.

2023-12-14 15:55 UTC, bslater2 commented
I submitted a new pull request (https://github.com/SBNSoftware/sbndaq-artdaq/pull/130) which is the updates to the trigger board reader code. The changes to the CAENV1730s and Analyzer modules were linked, they were with regards to recent changes from Lan in how the timestamps are created, when I commited them I didn't realise it would cause issues here, I will leave those changes to be in a pull request from her.

2023-12-14 15:55 UTC, closed without merging